import { Geist_Mono } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import "@/scroll/scrollbar.css"
import Script from "next/script";
import NavigationBar from "@/components/NavigationBar";
import Fotter from "@/components/Fotter";
import Themewrapper from "@/context/ThemeProvider";

const geist = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono", // CSS variable name
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair", // CSS variable name
});

export const metadata = {
  title: "Gcodes</>",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="dark"
      lang="en"
      className={`${geist.variable} ${playfair.variable}`}
    >
      <body>
        <Themewrapper>
          <div id="holder">
            <NavigationBar />
            {children}
            <Fotter />
          </div>
        </Themewrapper>
        <Script
          src="https://kit.fontawesome.com/4480df3da2.js"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
        <Script
          src="./scroll/scroll.js"
        />
      </body>
    </html>
  );
}
