import { Geist_Mono } from 'next/font/google';
import { Playfair_Display } from 'next/font/google';
import "./globals.css";
import Head from 'next/head';
import Script from 'next/script';

const geist = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono', // CSS variable name
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair', // CSS variable name
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dark" lang="en" className={`${geist.variable} ${playfair.variable}`}>
      <body>
        <div id='holder'>
          {children}
        </div>
        <Script 
          src="https://kit.fontawesome.com/4480df3da2.js" 
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </body>
    </ html>
  );
}
